window.GRAIN = [
    {
        "data":  "2026-08-28",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD06-RAL-V2",
        "investimento":  5.45,
        "impressoes":  108,
        "cliques":  0,
        "leads":  0,
        "cpm":  50.46,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-30",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD05-RAL-V2",
        "investimento":  0.22,
        "impressoes":  7,
        "cliques":  0,
        "leads":  0,
        "cpm":  31.43,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-29",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD03-RAL-V1",
        "investimento":  0.05,
        "impressoes":  1,
        "cliques":  0,
        "leads":  0,
        "cpm":  50,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-29",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD04-RAL-V2",
        "investimento":  0.06,
        "impressoes":  1,
        "cliques":  0,
        "leads":  0,
        "cpm":  60,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-31",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD05-RAL-V2",
        "investimento":  0.09,
        "impressoes":  5,
        "cliques":  0,
        "leads":  0,
        "cpm":  18,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-29",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD05-RAL-V2",
        "investimento":  4.49,
        "impressoes":  88,
        "cliques":  0,
        "leads":  0,
        "cpm":  51.02,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-28",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD02-RAL-V1",
        "investimento":  22.18,
        "impressoes":  381,
        "cliques":  21,
        "leads":  1,
        "cpm":  58.22,
        "cpc":  1.06,
        "ctr":  5.51,
        "cpl":  22.18
    },
    {
        "data":  "2026-08-30",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD02-RAL-V1",
        "investimento":  79.1,
        "impressoes":  1840,
        "cliques":  47,
        "leads":  8,
        "cpm":  42.99,
        "cpc":  1.68,
        "ctr":  2.55,
        "cpl":  9.89
    },
    {
        "data":  "2026-08-30",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD01-RAL-V1",
        "investimento":  0.22,
        "impressoes":  3,
        "cliques":  0,
        "leads":  0,
        "cpm":  73.33,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-31",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD04-RAL-V2",
        "investimento":  0.32,
        "impressoes":  8,
        "cliques":  0,
        "leads":  0,
        "cpm":  40,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-31",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD02-RAL-V1",
        "investimento":  31.58,
        "impressoes":  833,
        "cliques":  18,
        "leads":  4,
        "cpm":  37.91,
        "cpc":  1.75,
        "ctr":  2.16,
        "cpl":  7.9
    },
    {
        "data":  "2026-08-28",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD05-RAL-V2",
        "investimento":  20.14,
        "impressoes":  624,
        "cliques":  8,
        "leads":  1,
        "cpm":  32.28,
        "cpc":  2.52,
        "ctr":  1.28,
        "cpl":  20.14
    },
    {
        "data":  "2026-08-31",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD03-RAL-V1",
        "investimento":  0.19,
        "impressoes":  7,
        "cliques":  0,
        "leads":  0,
        "cpm":  27.14,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-29",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD02-RAL-V1",
        "investimento":  47.41,
        "impressoes":  970,
        "cliques":  29,
        "leads":  2,
        "cpm":  48.88,
        "cpc":  1.63,
        "ctr":  2.99,
        "cpl":  23.7
    },
    {
        "data":  "2026-08-28",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD03-RAL-V1",
        "investimento":  0.5,
        "impressoes":  7,
        "cliques":  0,
        "leads":  0,
        "cpm":  71.43,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-28",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD01-RAL-V1",
        "investimento":  0.07,
        "impressoes":  5,
        "cliques":  0,
        "leads":  0,
        "cpm":  14,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-29",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD06-RAL-V2",
        "investimento":  0.57,
        "impressoes":  15,
        "cliques":  0,
        "leads":  0,
        "cpm":  38,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    },
    {
        "data":  "2026-08-28",
        "campanha":  "RAL | E2-CAP | P2-FRIO | LEAD | CBO | 2026-08-28 | LAL",
        "conjunto":  "AUTO | ALL | 25 a 54 | BR | LAL 1% Seguidores",
        "anuncio":  "AD04-RAL-V2",
        "investimento":  0.07,
        "impressoes":  3,
        "cliques":  0,
        "leads":  0,
        "cpm":  23.33,
        "cpc":  0,
        "ctr":  0,
        "cpl":  null
    }
];
